### ISSUE TITLE
Problem with Splat Operator in model.rb

### ISSUE THREAD

**Issue by nikkij** [jisraelsen/unidata#2]
Using jruby 1.6.8 (ruby-1.8.7-p357) (2012-09-18 1772b40) (OpenJDK 64-Bit Server VM 1.6.0_24) [linux-amd64-java]

Trying to make a connection with:

Unidata.open_connection do
end

received 

tIDENTIFIER error for line 37

Removed the splat operator from in front of field.

Replaced this -
record.replace *field.index, field.to_unidata(value)

with
record.replace field.index, field.to_unidata(value)

and script runs.

**Comment by jisraelsen** [comment]
Thank you for reporting this!  I think this will end up being a problem specific to jruby running in 1.8 mode.  I have only been testing in 1.9 mode.  I will look into it, though.

I'm not sure the change you suggest will work for all cases.  The field index should be an array (again could be issue with 1.8 mode if it's not).  Having the index as an array allows for multivalued fields to be defined in the model.  For example:

``` ruby
class Product < Unidata::Model
  self.filename = 'PRODUCT'

  field 1, :name,
  field 2, :description
  field 3, :cost, Float
  field [4, 1], :available_on, Date
  field [4, 2], :created_on, Date
end
```

**Comment by jisraelsen** [comment]
Just release v0.0.7 that solves this problem.
